#index:
#    path: /
#    controller: App\Controller\DefaultController::index

upload_image:
    path: /upload-image
    controller: App\Controller\ImageController::uploadImage
    methods: [GET, POST]

home:
    path: /
    controller: App\Controller\HomeController::index

